name: Deploy Vite React App from subfolder

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: simbioz-landing

      - name: Build project
        run: npm run build
        working-directory: simbioz-landing

      - name: Check build output
        run: ls -la simbioz-landing/dist

      - name: Prepare dist contents
        run: |
          mkdir -p deploy_temp
          cp -r simbioz-landing/dist/* deploy_temp/

      - name: Deploy via SCP to REG.RU
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "deploy_temp/*"
          target: "www/simbioz-tech.ru"
          rm: true

      - name: Cleanup
        run: rm -rf deploy_temp
