name: Deploy Vite React App and Telegram Bot

on:
  push:
    branches:
      - master
    paths:
      - 'simbioz-landing/**'
      - 'simbioz-landing/server/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: simbioz-landing

      - name: Build project
        run: npm run build
        working-directory: simbioz-landing
        env:
          VITE_TELEGRAM_TOKEN: ${{secrets.VITE_TELEGRAM_TOKEN}}
          VITE_CHAT_IDS: ${{secrets.VITE_CHAT_IDS}}
          VITE_EMAILJS_SERVICE_ID: ${{secrets.VITE_EMAILJS_SERVICE_ID}}
          VITE_EMAILJS_TEMPLATE_ID: ${{secrets.VITE_EMAILJS_TEMPLATE_ID}}
          VITE_EMAILJS_PUBLIC_KEY: ${{secrets.VITE_EMAILJS_PUBLIC_KEY}}

      - name: Copy dist contents to top-level deploy folder
        run: |
          mkdir simbioz-tech.ru
          shopt -s dotglob
          cp -r simbioz-landing/dist/* simbioz-tech.ru/

      - name: Deploy ONLY dist contents (not the folder itself)
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "simbioz-tech.ru/*"                # ✅ только содержимое папки dist
          target: "www/"
          rm: true

      - name: Cleanup
        run: rm -rf simbioz-tech.ru

  deploy-telegram-bot:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if server files exist
        id: check-files
        run: |
          if [ -d "simbioz-landing/server" ] && [ "$(ls -A simbioz-landing/server)" ]; then
            echo "server_files_exist=true" >> $GITHUB_OUTPUT
            echo "✅ Server files found"
          else
            echo "server_files_exist=false" >> $GITHUB_OUTPUT
            echo "❌ No server files found, skipping bot deployment"
          fi

      - name: Setup Python
        if: steps.check-files.outputs.server_files_exist == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        if: steps.check-files.outputs.server_files_exist == 'true'
        run: |
          cd simbioz-landing/server
          pip install -r requirements.txt

      - name: Deploy Telegram Bot files
        if: steps.check-files.outputs.server_files_exist == 'true'
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "simbioz-landing/server/*"
          target: "www/server/"
          rm: true

      - name: Deploy and start Telegram Bot
        if: steps.check-files.outputs.server_files_exist == 'true'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd www/server
            chmod +x deploy.sh check_bot.sh restart_bot.sh
            ./deploy.sh

      - name: Notify Telegram Bot deployment
        if: always() && steps.check-files.outputs.server_files_exist == 'true'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.VITE_CHAT_IDS }}
          token: ${{ secrets.VITE_TELEGRAM_TOKEN }}
          message: |
            🤖 Telegram Bot Deployment
            
            Status: ${{ job.status }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            
            ${{ job.status == 'success' && '✅ Bot deployed successfully!' || '❌ Bot deployment failed!' }}
