name: Deploy Vite React App from subfolder

on:
  push:
    branches:
      - master

jobs:
  checkout-and-install:
    name: Checkout & Install Dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-node-modules.outputs.cache-hit }}
    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v3

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: simbioz-landing/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: 📦 Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install
        working-directory: simbioz-landing

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: checkout-and-install
    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v3

      - name: Build Vite project
        run: npm run build
        working-directory: simbioz-landing
        env:
          VITE_TELEGRAM_TOKEN: ${{ secrets.VITE_TELEGRAM_TOKEN }}
          VITE_CHAT_IDS: ${{ secrets.VITE_CHAT_IDS }}
          VITE_EMAILJS_SERVICE_ID: ${{ secrets.VITE_EMAILJS_SERVICE_ID }}
          VITE_EMAILJS_TEMPLATE_ID: ${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}
          VITE_EMAILJS_PUBLIC_KEY: ${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}

      - name: Prepare deploy directory (with dotfiles)
        run: |
          mkdir simbioz-tech.ru
          shopt -s dotglob
          cp -r simbioz-landing/dist/* simbioz-tech.ru/

      - name: Upload deploy folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy-folder
          path: simbioz-tech.ru

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download deploy folder artifact
        uses: actions/download-artifact@v3
        with:
          name: deploy-folder
          path: simbioz-tech.ru

      - name: 🚀 Deploy to remote server via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "simbioz-tech.ru/*"
          target: "www/"
          rm: true

      - name: 🧹 Cleanup deploy artifacts
        run: rm -rf simbioz-tech.ru
