name: Deploy Vite React App and Telegram Bot

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: simbioz-landing

      - name: Build project
        run: npm run build
        working-directory: simbioz-landing
        env:
          VITE_TELEGRAM_TOKEN: ${{secrets.VITE_TELEGRAM_TOKEN}}
          VITE_CHAT_IDS: ${{secrets.VITE_CHAT_IDS}}
          VITE_EMAILJS_SERVICE_ID: ${{secrets.VITE_EMAILJS_SERVICE_ID}}
          VITE_EMAILJS_TEMPLATE_ID: ${{secrets.VITE_EMAILJS_TEMPLATE_ID}}
          VITE_EMAILJS_PUBLIC_KEY: ${{secrets.VITE_EMAILJS_PUBLIC_KEY}}

      - name: Copy dist contents to top-level deploy folder
        run: |
          mkdir simbioz-tech.ru
          shopt -s dotglob
          cp -r simbioz-landing/dist/* simbioz-tech.ru/

      - name: Deploy ONLY dist contents (not the folder itself)
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "simbioz-tech.ru/*"                # ✅ только содержимое папки dist
          target: "www/"
          rm: true

      - name: Cleanup
        run: rm -rf simbioz-tech.ru

  deploy-telegram-bot:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if server files exist
        id: check-files
        run: |
          echo "Checking for server files..."
          ls -la simbioz-landing/ || echo "simbioz-landing directory not found"
          if [ -d "simbioz-landing/server" ]; then
            echo "simbioz-landing/server directory found"
            ls -la simbioz-landing/server/
            if [ "$(ls -A simbioz-landing/server)" ]; then
              echo "server_files_exist=true" >> $GITHUB_OUTPUT
              echo "✅ Server files found"
            else
              echo "server_files_exist=false" >> $GITHUB_OUTPUT
              echo "❌ Server directory is empty"
            fi
          else
            echo "server_files_exist=false" >> $GITHUB_OUTPUT
            echo "❌ Server directory not found"
          fi

      - name: Setup Python
        if: steps.check-files.outputs.server_files_exist == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        if: steps.check-files.outputs.server_files_exist == 'true'
        run: |
          cd simbioz-landing/server
          pip install -r requirements.txt
        env:
          VITE_TELEGRAM_TOKEN: ${{secrets.VITE_TELEGRAM_TOKEN}}
          VITE_CHAT_IDS: ${{secrets.VITE_CHAT_IDS}}

      - name: Deploy Telegram Bot files
        if: steps.check-files.outputs.server_files_exist == 'true'
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "simbioz-landing/server/*"
          target: "www/server/"

      - name: Deploy and start Telegram Bot
        if: steps.check-files.outputs.server_files_exist == 'true'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Creating server directory..."
            mkdir -p www/server
            echo "Checking server files..."
            ls -la www/server/simbioz-landing/server/
            echo "Setting permissions..."
            chmod +x www/server/simbioz-landing/server/deploy.sh www/server/simbioz-landing/server/check_bot.sh www/server/simbioz-landing/server/restart_bot.sh
            echo "Running deploy script..."
            cd www/server/simbioz-landing/server/
            VITE_TELEGRAM_TOKEN="${{ secrets.VITE_TELEGRAM_TOKEN }}" ./deploy.sh

      - name: Notify Telegram Bot deployment
        if: always() && steps.check-files.outputs.server_files_exist == 'true'
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.VITE_TELEGRAM_TOKEN }}
          message: |
            🤖 Telegram Bot Deployment
            
            Status: ${{ job.status }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            
            ${{ job.status == 'success' && '✅ Bot deployed successfully!' || '❌ Bot deployment failed!' }}
