name: Deploy Vite React App from subfolder

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: simbioz-landing

      - name: Build project
        run: npm run build
        working-directory: simbioz-landing

      - name: Deploy only contents of dist/ via SCP to REG.RU
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "simbioz-landing/dist/*"     # ⚠️ Только содержимое dist
          target: "www/simbioz-tech.ru"
          rm: true                              # Удалить старые файлы перед загрузкой

      - name: Done
        run: echo "✅ Deployment complete"
