name: Deploy Vite React App from subfolder

on:
  push:
    branches:
      - master

jobs:
  checkout:
    name: Checkout repository
    runs-on: ubuntu-latest
    outputs:
      repo-path: ${{ steps.checkout.outputs.path }}
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4.2.2

  install-dependencies:
    name: Install dependencies
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install npm dependencies
        run: npm install
        working-directory: simbioz-landing

  build:
    name: Build project
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Build project
        run: npm run build
        working-directory: simbioz-landing
        env:
          VITE_TELEGRAM_TOKEN: ${{secrets.VITE_TELEGRAM_TOKEN}}
          VITE_CHAT_IDS: ${{secrets.VITE_CHAT_IDS}}
          VITE_EMAILJS_SERVICE_ID: ${{secrets.VITE_EMAILJS_SERVICE_ID}}
          VITE_EMAILJS_TEMPLATE_ID: ${{secrets.VITE_EMAILJS_TEMPLATE_ID}}
          VITE_EMAILJS_PUBLIC_KEY: ${{secrets.VITE_EMAILJS_PUBLIC_KEY}}

  prepare-artifacts:
    name: Prepare artifacts for deployment
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Copy dist contents
        run: |
          mkdir simbioz-tech.ru
          shopt -s dotglob
          cp -r simbioz-landing/dist/* simbioz-tech.ru/

  deploy:
    name: Deploy to production
    needs: prepare-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Copy dist contents
        run: |
          mkdir simbioz-tech.ru
          shopt -s dotglob
          cp -r simbioz-landing/dist/* simbioz-tech.ru/

      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "simbioz-tech.ru/*"
          target: "www/"
          rm: true

  cleanup:
    name: Cleanup
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Remove temporary files
        run: rm -rf simbioz-tech.ru