name: Deploy Vite React App from subfolder

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: simbioz-landing

      - name: Build project
        run: npm run build
        working-directory: simbioz-landing
        env:
          VITE_TELEGRAM_TOKEN: ${{secrets.VITE_TELEGRAM_TOKEN}}
          VITE_CHAT_IDS: ${{secrets.VITE_CHAT_IDS}}
          VITE_EMAILJS_SERVICE_ID: ${{secrets.VITE_EMAILJS_SERVICE_ID}}
          VITE_EMAILJS_TEMPLATE_ID: ${{secrets.VITE_EMAILJS_TEMPLATE_ID}}
          VITE_EMAILJS_PUBLIC_KEY: ${{secrets.VITE_EMAILJS_PUBLIC_KEY}}

      - name: Copy dist contents to top-level deploy folder
        run: |
          mkdir simbioz-tech.ru
          cp -r simbioz-landing/dist/* simbioz-tech.ru/

      - name: Deploy ONLY dist contents (not the folder itself)
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "simbioz-tech.ru/*"                # ✅ только содержимое папки dist
          target: "www/"
          rm: true

      - name: Cleanup
        run: rm -rf simbioz-tech.ru
