name: Deploy Vite React App from subfolder

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: simbioz-landing

      - name: Build project
        run: npm run build
        working-directory: simbioz-landing

      - name: Deploy ONLY contents of dist/ via SCP (no extra folder)
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "simbioz-landing/dist/**"   # ✅ только содержимое, включая вложенные папки
          target: "www/simbioz-tech.ru"
          rm: true                            # очистка перед деплоем

